version: '3.4'
services:
  arangdb:
    image: arangodb
    ports:
    - "8529:8529"
    environment:
    - ARANGO_RANDOM_ROOT_PASSWORD=1
  baseimage: 
    image: python:3.6.8-alpine3.8
  rabbitmq:
    image: rabbitmq:3.7.8-alpine
    ports:
    - "8080:15672"
